/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "dqreqxupxhwqbmcqvdnt"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxcmVxeHVweGh3cWJtY3F2ZG50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1OTM2MDYsImV4cCI6MjA3NzE2OTYwNn0.7bMAKomeL7vfcqu0T-n9ME2XJtwO-ByT8NSmxBRPxa8"